---
  - name: Download Zabbix Debian 8 release deb file
    get_url: 
      url="http://repo.zabbix.com/zabbix/3.0/debian/pool/main/z/zabbix-release/zabbix-release_3.0-1+jessie_all.deb"
      dest="/tmp/zabbix-release_3.0-1.deb"
    when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"
    
  - name: Download Zabbix Debian 7 release deb file
    get_url: 
      url="http://repo.zabbix.com/zabbix/3.0/debian/pool/main/z/zabbix-release/zabbix-release_3.0-1+wheezy_all.deb"
      dest="/tmp/zabbix-release_3.0-1.deb"
    when: ansible_distribution == "Debian" and ansible_distribution_major_version == "7"
    
  - name: Download Zabbix Ubuntu 14 release deb file
    get_url: 
      url="http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-1+trusty_all.deb"
      dest="/tmp/zabbix-release_3.0-1.deb"
    when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

  - name: Download Zabbix Ubuntu 16 release deb file
    get_url: 
      url="http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-1+xenial_all.deb"
      dest="/tmp/zabbix-release_3.0-1.deb"
    when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

  - name: Download Zabbix Ubuntu 18 release deb file
    get_url: 
      url="http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-2+bionic_all.deb"
      dest="/tmp/zabbix-release_3.0-1.deb"
    when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"

  - name: Apt install Zabbix release in Ubuntu/Debian
    apt: deb="/tmp/zabbix-release_3.0-1.deb"
    when: ansible_os_family == "Debian"
    register: result_zabbix_release

  - name: Apt-get update
    apt: update_cache=yes
    when: ansible_os_family == "Debian" and result_zabbix_release|changed

  - name: Yum install Zabbix release in RHEL or CentOS
    yum: name=http://repo.zabbix.com/zabbix/3.0/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-3.0-1.el{{ ansible_distribution_major_version }}.noarch.rpm
    when: ansible_os_family == "RedHat"
    
  - name: Apt install Zabbix agent
    apt: name=zabbix-agent
    when: ansible_os_family == "Debian"

  - name: Yum install Zabbix agent
    yum: name=zabbix-agent
    when: ansible_os_family == "RedHat"
