---
  - name: Start Zabbix agent service
    service: name=zabbix-agent state=started
    register: zabbix_installed
    ignore_errors: yes

  - include: install.yaml
    when: zabbix_installed|failed

  - include: configure.yaml

  - name: Start Zabbix agent service
    service: name=zabbix-agent state=started
